### ISSUE TITLE
Clicking "Add result" in French causes an exception

### ISSUE THREAD

**Issue by KennyMonster** [mercycorps/TolaActivity#1041]
1. Change your language to French in the profile
2. Navigate to: https://tola-activity.mercycorps.org/program/542/0/0/
3. Expand the first indicator, scroll down, and click "Add results" (in french: "Ajouter des résultats")

Exception:

```
2019-01-06 23:30:24,833 ERROR    django.request Internal Server Error: /indicators/collecteddata_add/569/5777/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/www/TolaActivity/indicators/views/views_indicators.py", line 735, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 213, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/var/www/TolaActivity/indicators/views/views_indicators.py", line 738, in get_context_data
    context = super(CollectedDataCreate, self).get_context_data(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 93, in get_context_data
    kwargs['form'] = self.get_form()
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 45, in get_form
    return form_class(**self.get_form_kwargs())
  File "/var/www/TolaActivity/indicators/forms.py", line 179, in __init__
    choices.append((pt.id, str(pt)))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 595, in __str__
    return force_text(self).encode('utf-8')
  File "/usr/local/lib/python2.7/site-packages/django/utils/encoding.py", line 88, in force_text
    raise DjangoUnicodeDecodeError(s, *e.args)
DjangoUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128). You passed in <PeriodicTarget: [Bad Unicode data]> (<class 'indicators.models.PeriodicTarget'>)
```

The problem is in `PeriodicTarget.__unicode__` which calls `l10n_date_medium()`:

```
    def __unicode__(self):
        """outputs the period name (see period_name docstring) followed by start and end dates

        used in collect data form"""
        period_name = self.period_name

        if period_name and self.start_date and self.end_date:
            # e.g "Year 1 (date - date)" or "Quarter 2 (date - date)"
            return u"{period_name} ({start_date} - {end_date})".format(
                period_name=period_name,
                start_date=l10n_date_medium(self.start_date),
                end_date=l10n_date_medium(self.end_date)
            )
        elif period_name:
            # if no date for some reason but time-based frequency:
            return unicode(period_name)

        return self.period
```

`l10n_date_medium()` currently returns a str(). When it contains a localized month with unicode in it, the str -> unicode conversion fails in the `.format()`.

**Comment by RickieT** [comment]
I am looking at this now on qa server

**Comment by KennyMonster** [comment]
Regarding testing/reproduction of the issue, the exception only happens when an indicator contains a target period start/end date that contains a non-ASCII character in the name.

The first indicator on program TolaData Demo (1.1 Number of reported incidents of violence) has a start/end date range of "1 jan. 2016 - 31 déc. 2016". Because December, localized to FR, contains an accent, the exception happens.

Other indicators without target periods, or with months without unicode chars will work fine.

**Comment by RickieT** [comment]
Verification complete: 
* Clicking Add results in all languages available did not cause any issues to occur after multiple attempts.
